### ISSUE TITLE
How to find authentication token?

### ISSUE THREAD

**Issue by moman822** [MarkEdmondson1234/googleAuthR#182]
How can I find my authentication token, so that I can use it in a different environment? I'm not able to use the login process there (running program in docker container) so need to reference the token directly.

I see in [this](https://cran.r-project.org/web/packages/googleAuthR/vignettes/google-authentication-types.html) documentation for an older version of `gar_auth()`:

> If you supply a filename to googleAuthR::gar_auth(token = "filename") then it will save the token there. If it doesn’t exist, it will make a new one, if it does exist it will attempt to read the token from that file. Relative and absolute filenames work.

Is there something like that I can do now to save the token?

**Comment by MarkEdmondson1234** [comment]
You’re needing non-interactive auth for servers I think? The recommendation is to use a JSON service key instead, but if you want to keep using the Oauth2 token you can change the folder the gargle token is saved to a local folder rather than a global one. There is a link on the website for a discussion on gargles website.

**Comment by moman822** [comment]
Yes, that is correct. Is using the JSON service key possible only when working with your own project (I'm using your `googleAnalyticsR` package)? I'll have a closer look at gargle as well.

**Comment by MarkEdmondson1234** [comment]
Yes you need your own project, and will do anyway as the default client project won’t work on servers. 

The latest version of googleAnalyticsR has a setup function (ga_setup()) that helps walk you through setting up your service key, and you can now use ga_auth(json_file = “yourkey.json”) to use it. It’s only on the dev version of GitHub though at the moment.

**Comment by moman822** [comment]
Hi @MarkEdmondson1234 , I thought I'd sorted out the authentication by creating a Service Account on my own GCP project, and using the JSON key with `googleAuthR::gar_auth_service(json_file='key.json')`. This worked locally for me in a fresh R session to then follow up with some successful calls from `googleAnalyticsR` (no email selection prompt,etc.). I also saw the errors ref'd above when I hadn't added the service account to my Analytics properties; it worked once I did.

However, it did not work for me in the server environment, seeing the error: 
```
The default Google Cloud Project for googleAnalyticsR is intended 
           
for evalutation only, not production scripts.  
           
Please set your own client.id and client.secret via googleAuthR::gar_set_client()
```

So point of confusion one is that I guess the service account authentication was still going through the default project? This wasn't clear to me.

A second point would be when following your documentation (http://code.markedmondson.me/googleAnalyticsR/articles/setup.html#setting-up-clientid-manually) there is no longer an "Other" option for creating an Oauth client ID on GCP, from what I see.

Following from the same point in your documentation, it shows:
```
googleAuthR::gar_set_client("~/dev/auth/gcp_client.json")
library(googleAnalyticsR)
ga_auth()
```

I tried this method with both "Desktop app" and "Web application"application type keys, both prompt me to login via the browser. To use via server, I don't want to need to login. Do you know what step I am missing? I am not using the development packages.

Apologies for troubleshooting q's. I have been reading over the documentation, GCP documentation and making lots of attempts but still can't sort out the authentication flow.

**Comment by smach** [comment]
Hi @moman822 . A couple of thoughts, since I've spent a lot of time trying to get this to work on servers, too. Does your _server_ R environment have all the same environment variables as well as all the files as your local system? In other words, did you run all the `ga_auth_setup() `steps in an R session on your server or copy all the environment variables to the server's .Renviron file? If it's a Shiny app, are you setting all the appropriate environment variables in your app?

**Comment by moman822** [comment]
I have not tried to mess around with environment variables, and am trying to avoid needing the dev version (where `ga_auth_setup()` resides) of either package (`googleAuthR` & `googleAnalyticsR`). Ideally I can get it sorted to just point to one or two of the JSON keys I get from GCP on my server, which the documentation suggests is possible [here](https://code.markedmondson.me/googleAuthR/articles/google-authentication-types.html#authentication-with-a-json-file-via-service-accounts).

Right now I don't seem to be able to get any authentication locally or on my server with _my_ GCP project/app/thing.

I am currently stuck thinking I need some combination of `googleAuthR::gar_set_client()` and `googleAuthR::gar_auth_service()` and that I have the wrong setup on the GCP end.

As I mentioned above, there is not an "Other" option when creating an Oauth Client ID on GCP. I've done it for "Web app", "Desktop application", and "TVs and Limited Input Devices" with the same results.

I am trying like this:
```
googleAuthR::gar_set_client(json = "path/to/client-id-key.json")

googleAuthR::gar_auth_service(json_file = "path/to/service-account-key.json")
```

 These execute fine, then if I try to do something from `googleAnalyticsR` that calls the API, like:
```
ga_account_list()
```
I get an error:
```
Request Status Code: 403
Error: API returned: Insufficient Permission: Request had insufficient authentication scopes.
```

checking scopes like this: `getOption("googleAuthR.scopes.selected")` looks OK:
```
[1] "https://www.googleapis.com/auth/analytics"               "https://www.googleapis.com/auth/analytics.readonly"     
[3] "https://www.googleapis.com/auth/analytics.edit"          "https://www.googleapis.com/auth/analytics.manage.users" 
[5] "https://www.googleapis.com/auth/analytics.user.deletion"
```

**Comment by MarkEdmondson1234** [comment]
From the version on github onwards, if using a json service key you will be able to skip the client.id setting (as it’s already implied in the json key)

But before then on a server it needs to be set. Each time you change the client.id settings or scopes you need to re-auth to cache the new settings. 

Which server are you running on? There was an issue on shinyapps.io where options were ignored. 

The “Other” option changed name recently in GCP console, will need to update docs, but it should be a json file with the field “installed” - there should be a message when you use googleAuthR::gar_set_client() if set successfully. 

On a server I think env args are the safest way to ensure the settings are set to what you need with auto authentication. 

Otherwise Sys.setenv() can be used in scripts at the top. 

Code wise it should look like (CRAN versions)

‘’’r
#...set env args if using them

# load library - will use env args
library(googleAnalyticsR)

# set you own client
googleAuthR::gar_set_client()

# auth with your service account
googleAuthR::gar_service_auth()
‘’’

Dev versions:

‘’’r
library(googleAnalyticsR)
ga_auth(json_file=“service.json”)
‘’’

If that’s not working could you show the code you are trying with options(googleAuthR.verbose=2) to give some more logging info. I guess setting the client.id is failing somewhere.

**Comment by moman822** [comment]
That worked!

```
library(googleAnalyticsR)
googleAuthR::gar_set_client("key.json")
googleAuthR::gar_auth_service("service-key.json")
```
got the job done. I must have run those two commands dozens of times yesterday but neglected to load `googleAnalyticsR` first.

FWIW I am using just some AWS servers, running scripts in a Docker container. It's working locally, I'll report back if there is an issue in production.

FYI it seems to work with the "Desktop app" type key, which has the 'installed' field (which has all the same fields as the "Limited input" type app).

Thanks.

**Comment by MarkEdmondson1234** [comment]
Ok, yes loading googleAnalyticsR sets the default client if its not set in an environment arg, so if setting manually you need to overwrite that setting after its loaded. 

Docker containers were motivation to use environment arguments as you can then pass them in on Docker container launch, since if it were me I would not keep the service-key in a Docker container for security reasons - the client.json is fine to keep in though. 

I'll mark this solved though now for now :)  Thanks for the feedback, will change some docs.
