### ISSUE TITLE
Refreshing web page with login button

### ISSUE THREAD

**Issue by explodecomputer** [MarkEdmondson1234/googleAuthR#26]
Hi

Thank you for this package, it is fantastic.

I'm sort of unfamiliar with the way google does authentication, just wondering if you can offer me some advice. Here is a minimal example of what I'm trying to do: 

```
runGist("ef4341872582719d6b73", port=4018)
```

There is a login button, and when you login the server renders the 'Logged in' menu item. This works great, but I have a small issue - it changes the url after I click the log in button to something that looks like `http://127.0.0.1:4018/?state=UPWBX3ymhlEBT2xypCco&code=4/VDtX2DNs_fR05smRm1zZ-DMqrz4-H5ghqOPCBtlR6a8#`. Is there anyway this can be avoided? After logging in, if i refresh the web page for whatever reason I get an error that looks like this:

```
Request: https://www.googleapis.com/oauth2/v1/userinfo/
Warning in retryRequest(do.call(request_type, args = arg_list, envir = asNamespace("httr"))) :
  Request Status Code: 401
Warning in retryRequest(do.call(request_type, args = arg_list, envir = asNamespace("httr"))) :
  JSON fetch error: Invalid Credentials
Warning in retryRequest(do.call(request_type, args = arg_list, envir = asNamespace("httr"))) :
  No retry attempted: Invalid Credentials
Error in checkGoogleAPIError(req) : JSON fetch error: Invalid Credentials
```

Sorry if this is the wrong place to be posting this. Would be grateful for any help!

Thanks

**Comment by MarkEdmondson1234** [comment]
Hi there, thanks for trying the package :)

I'm afraid having the state and code parameters in the URL are essential to get Google authorised.  I did look at redirecting the page afterwards to a nicer URL, but this isn't easy in Shiny without using client side javascript.  If anyone has an alternative better idea let me know.

Whats happening is after login you actually reload the Shiny app but with the correct authorisation codes in the URL, that are read into Shiny.  `state` is random string generated each app that makes sure you are the same person who authorised in Google, which is why it errors if you refresh as if this doesn't match, it will fail.  This is necessary to stop people copy-pasting the URL and having access to your stuff. `code` is the authroisation code used to sign API requests. 

Practically, this means I  tend to in my apps have a "Start Again" button which links back to the start page, which will reload the app to its initial state.

**Comment by marekrogala** [comment]
@MarkEdmondson1234 I can see that this issue is "closed". Does this mean that this problem has been fixed or is it still present but won't be fixed? Is there any workaround better than having a "Start again" button?

I don't know exactly how the googleAuthR package works so I'm not sure I fully get why we have this problem... I mean, on some websites you often go to different addresses and your google session is still live. Why is Shiny different? Would storing the parameters in a cookie help? Or is the problem on the server side? Could you elaborate on why this error happens?

**Comment by MarkEdmondson1234** [comment]
Hi @marekrogala - quick answer is to use the JavaScript auth instead, which means no reload of the page by using `gar_auth_jsUI` and its module `gar_auth_js`

Longer answer is the original method generates the state and verification code server side in R, sends you to Google to authenticate, then back to a different Shiny session for login.  This is tied to Shiny not keeping state when the URL reloads.  I'm looking into ways to get around that using webhooks via https://github.com/MarkEdmondson1234/googleAuthR/issues/71 but for most purposes, the JavaScript version avoids the reload and also works in RMarkdown so usually the solution.

**Comment by marekrogala** [comment]
@MarkEdmondson1234 thanks! the problem we're trying to solve is what happens when user refreshes the page (e.g. hits F5). Will using the JS auth help with that?
What exactly does the package need to keep in the state on the server? Maybe this could be kept e.g. in a database, a local file, or in an encrypted cookie?

**Comment by MarkEdmondson1234** [comment]
@marekrogala Hmm I don't think the JS auth will help in that scenario.  Perhaps you will get what you want by setting the `access_type` to `offline` (default `online`)

```r
shiny::callModule(googleAuth, "your_ui_name", login_text = "Login", access_type = "offline")
```

...which despite the name means and combined with the default `approval_prompt = "auto"` will at least mean a user will log in automatically if they have already when they come back from the auth.   

I think this is because a cookie is dropped by Google, but do confirm this.  That used to be the default but I changed it due to privacy questions, so you may want to mention something about it on the text.  

If its not a perfect solution then feel free to open a new issue with a spec of the new behaviour - since this library was written bookmarkable state has come out for Shiny too that may be a workaround.

**Comment by mateuszwyszynski** [comment]
Hi @MarkEdmondson1234. I followed your advice and set the parameter `access_type` to `offline` but sadly this does not help. 

After refreshing the page it seems like the user is still logged in and we still have his token, but when trying to call `get_user_info` you get an error saying that the credentials are invalid.

**Comment by MarkEdmondson1234** [comment]
Hard to say without seeing the error, but possibly the security code is different (its refreshed per Shiny session - you can hard code it via `options(googleAuthR.securitycode = "yourcode")`
