### ISSUE TITLE
Shinyapps.io Issues

### ISSUE THREAD

**Issue by debsush** [MarkEdmondson1234/googleAuthR#34]
Hi,

I am new to this world so excuse my ignorance.  I have a webapp on shinyapps.io. called https://dmarket.shinyapps.io/Main.  I want users to my webapp login using Google Auth. using httr package and also be able to share contents from my app onto their facebook timeline.  I am using Rfacebook package for this.  When I run the ui.R and server.R locally, everything works just fine but when executed over shinyapps.io, it does not work.  I raised the question in multiple forums (shinyapps forum, httr hithub, Rfacebook github) but no one had a solution to it.  It seems that shinyapps.io does not allow callback URI over port 1440.  Was wondering if you have been able to find any workaround while creating your package so that multiple users can login in my webapp (hosted over shinyapps.io) using their google logins

Appreciate your guidance and apologies if my question seems redundant

Thank you
SD

**Comment by MarkEdmondson1234** [comment]
Hi there, 
When deployed on the web such as shinyapps.io the redirect from the Google OAuth flow goes to normal web port 80, so you only need to worry about the port for local use. Make sure in your Google project you have https://dmarket.shinyapps.io/Main indicated as an allowed redirect. (See setup steps in readme)
It's important to allow the parameters such as ?state and ?code be read from the URL of the shiny session as that's needed for authentication, so watch out for iframes etc. 
I run several apps in shinyapps.io just so you know it works. Try deploying the example app now available in 0.3.0 so you can get an idea of how it works. 
Yours sincerely,Mark



On Sat, May 21, 2016 at 4:49 AM -0700, "debsush" <notifications@github.com> wrote:












Hi,



I am new to this world so excuse my ignorance.  I have a webapp on shinyapps.io. called https://dmarket.shinyapps.io/Main.  I want users to my webapp login using Google Auth. using httr package and also be able to share contents from my app onto their facebook timeline.  I am using Rfacebook package for this.  When I run the ui.R and server.R locally, everything works just fine but when executed over shinyapps.io, it does not work.  I raised the question in multiple forums (shinyapps forum, httr hithub, Rfacebook github) but no one had a solution to it.  It seems that shinyapps.io does not allow callback URI over port 1440.  Was wondering if you have been able to find any workaround while creating your package so that multiple users can login in my webapp (hosted over shinyapps.io) using their google logins



Appreciate your guidance and apologies if my question seems redundant



Thank you

SD

**Comment by debsush** [comment]
Thank you for the confirmation Mark - this was very encouraging.  However, the link https://github.com/MarkEdmondson1234/googleAuthR/blob/master/inst/shiny/shiny-example.R shows a 404 Error.  So I tried the https://mark.shinyapps.io/googleAuthRexample/  and on clicking the Login via google button I get the following error message
400. That’s an error.
Error: redirect_uri_mismatch
Application: googleAuthR
You can email the developer of this application at:me@markedmondson.me
The redirect URI in the request, https://mark.shinyapps.io/googleAuthRexample/, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/201908948134-cjjs89cffh3k429vi7943ftpk3jg36ed.apps.googleusercontent.com?project=201908948134 to update the authorized redirect URIs.
Learn more
Request Details
That’s all we know.

**Comment by MarkEdmondson1234** [comment]
Hi @debsush I forgot to take my own advice and forgot to add the app URL (https://mark.shinyapps.io/googleAuthRexample/ ) to the Google API console 
https://console.developers.google.com/apis/credentials/oauthclient/201908948134-cjjs89cffh3k429vi7943ftpk3jg36ed.apps.googleusercontent.com?project=g-auth-r

I have just added it so it should be working in the next 10 minutes! :)

**Comment by debsush** [comment]
Yes, it works like a charm now. Many many many thanks.  You made my day.  I wish facebook also allowed redirect to port 80.  :(
