### ISSUE TITLE
.httr-oauth file expiration..?

### ISSUE THREAD

**Issue by SimonHasager** [MarkEdmondson1234/googleAuthR#50]
Hi Mark,

Long time no see. I've started to use your amazing packages quite a lot. And it's been a pleasure! However, I've faced an issue. It's seems like the .httr-oauth file created with `gar_auth()` expires after one hour, which means that I can't create automated daily extracts of GA data :-(

Everything works just fine when I run my R scripts (both in RStudio and the Command Prompt) within one hour after creating the .httr-oauth file. But after one hour (or the next day) I get this error:

```
Walking through data.
Request to profileId:  ()
Error in f(content, ...) : Invalid Credentials
```

Then, if I delete the .httr-oauth file (and thereby force it to create a new file) or run `gar_auth(new_user=TRUE)`, it will all work again.

Can the .httr-oauth file expire? Or is it just me being a rookie? I hope you can help me.

Here is some sample code:

```
## Set working directory
setwd("my/project/folder/path")

## Load libraries (I have installed the most recent CRAN versions)
library(googleAuthR)
library(googleAnalyticsR)

## My googleAuthR client
options("googleAuthR.client_id" = "my.authR.client.id")
options("googleAuthR.client_secret" = "my_authR_client_secret")
options("googleAuthR.scopes.selected" = "https://www.googleapis.com/auth/analytics.readonly")

## My googleAnalyticsR client
options("googleAnalyticsR.client_id" = "my.analyticsR.client.id")
options("googleAnalyticsR.client_secret" = "my.analyticsR.client.secret")

## Both clients have the authorized redirect URI set to http://localhost:1410/
## I have tried using the default googleAuthR client, but the issue is the same

## Set GA view ID
viewID <- 123456789

## Read (or create) .httr-oauth file
gar_auth()

## Set date range (to yesterday)
start <- as.character(Sys.Date() - 1)
end <- as.character(Sys.Date() - 1)

## Fetch some data
ga <- google_analytics(
  viewID,
  start = start,
  end = end,
  metrics = c("sessions", "bounces"),
  dimensions = c("date", "channelGrouping"),
  samplingLevel = "WALK",
  max = 999999999
)
```

**Comment by MarkEdmondson1234** [comment]
Hi Simon, hope alls well :)

Yes the prime function of the httr token is to be used to refresh after the current authentication is over, so something is going wrong when it tries to refresh.

It sometimes happens if the client_id/secret you authenticated with is different from the one you are refreshing.  It looks like you are setting a lot of client Ids there, so I would remove some of those - it shouldn't be necessary to set them in googleAuthR as well as googleAnalyticsR.

Start first with the default project of googleAnalyticsR and once working you have something to go back to when you try your own project.  The auth keys need to be set exactly the same when authenticating first time and subsequent times, which is set when you load the library.   If setting your own client Ids, it needs to be after loading the library but before you call ga_auth() (note not gar_auth() )

You also should not be setting the redirect to port 1410, thats taken care of by httr itself.

If all else fails, try using the gar_auth_service() function instead, which requires you download the JSON file.  That doens't need refreshing and is recommended for automated scripts, but you will need to add the service account email (blablahblah@project.google.com) as a Viewer to the GA View you are downloading from.   You can then set that in an environment variable so you get auto-authenticated when you load the library (when using the github version - see README)

So, modifying your code:

```r
## Set working directory
setwd("my/project/folder/path")

## Just load this one
library(googleAnalyticsR)

## My googleAnalyticsR client
## try without this first.
##options("googleAnalyticsR.client_id" = "my.analyticsR.client.id")
##options("googleAnalyticsR.client_secret" = "my.analyticsR.client.secret")

## Set GA view ID
viewID <- 123456789

## Read (or create) .httr-oauth file
ga_auth()

## or googleAuthR::gar_auth_service("json_file.json")

## Set date range (to yesterday)
start <- as.character(Sys.Date() - 1)
end <- as.character(Sys.Date() - 1)

## Fetch some data
ga <- google_analytics(
  viewID,
  start = start,
  end = end,
  metrics = c("sessions", "bounces"),
  dimensions = c("date", "channelGrouping"),
  samplingLevel = "WALK",
  max = 999999999
)
```

Good luck! Hope it helps.

**Comment by SimonHasager** [comment]
Thanks a lot, Mark!

I got it to work with `googleAnalyticsR::ga_auth()` and the default project of googleAnalyticsR. However, I still had some issues when trying to use my own client.

So, I tried the `googleAuthR::gar_auth_service()` function and it works perfectly! It has been running for four days now without any failures.

**The solution:**
I created a Service Account Key and downloaded the JSON file.
I gave the App Engine default service account email (`my-project@appspot.gserviceaccount.com`) read & analyze access to the GA View.
In my R script, I authenticate using `googleAuthR::gar_auth_service(json_file="MyProject-blablabla.json")`.
