### ISSUE TITLE
Authentication for each shiny app user separately (Multiple google sheet Auth) 

### ISSUE THREAD

**Issue by prudhviraju535** [MarkEdmondson1234/googleAuthR#65]
I am using google sheets for the data import in the Shiny application. I want to deploy the Shiny app on the server so that everyone in the team can use.
I want to provide an option where each user can authorize there own gmail ID and get data from there google sheet. as of now only one single gmail account is getting authorized on the server side.

Please let me how can i achieve this.

**Comment by MarkEdmondson1234** [comment]
Hmm that is a little harder than most, because ironically although this library derived from https://github.com/jennybc/googlesheets, its not compatible with its authentication method AFAIK.  I don't think googlesheets supports multi-user Google auth in Shiny yet, but paging @jennybc just in case. Oh see you already have the issue open :) https://github.com/jennybc/googlesheets/issues/303

**Comment by MarkEdmondson1234** [comment]
I would really like to, but I think I was holding off until httr2 was being worked on via this issue.
https://github.com/hadley/httr/issues/351

My issue for making it work for any httr derived library is here: https://github.com/MarkEdmondson1234/googleAuthR/issues/39 although

**Comment by jennybc** [comment]
I am going to work on googlesheets once readxl is out the door. And a Google Drive client. So I definitely will revisit "how to do Google auth?" in the coming months.

googlesheets still uses my stuff, that formed the seed for this package. So I need to catch up on what's happened here, because I know it's more mature and general. To make things more complicated, @craigcitro has another option gestating https://github.com/ropenscilabs/gauth. And @MarkEdmondson1234 you're right -- httr2 will eventually be a thing. Basically things are very unsettled! 🤔

**Comment by prudhviraju535** [comment]
Thanks @MarkEdmondson1234 &@jennybc for the reply. i really waiting for the muti auth to be implemented in the packages. like authentication can be triggered in the client side but not on the server and save the Auth file in the individual cache until the session runs. This really helps each one to access there own Gsheets when Shiny app is deployed in the larger scale.

**Comment by MarkEdmondson1234** [comment]
Lets follow this on the other threads linked.
